version: "3"

services:
  ui:
    build:
      dockerfile: Dockerfile.development
    volumes:
      - ./ui/app:/app
    ports:
      - "8071:8071"
    command: >
      sh -c " \
        npm install -g npm@latest && \
        yarn global add vite && \
        yarn install && \
        npx browserslist@latest --update-db && \
        yarn dev --host 0.0.0.0 --port 8071 \
      "
  api:
    ports:
      - "5071:5000"
  db:
    ports:
      - "54371:5432"
