version: '3'

services:
  ui:
    build:
      context: ui
      args:
        GIT_VERSION: "${GIT_VERSION}"
        GIT_BRANCH: "${GIT_BRANCH}"
        GIT_LASTCOMMITDATE: "${GIT_LASTCOMMITDATE}"
    image: ui
    hostname: ui
    depends_on:
      - api
    restart: unless-stopped
    env_file: .env
  api:
    build:
      context: api
    hostname: api
    restart: unless-stopped
    volumes:
      - ./api/app:/app
      - ./.git:/app/.git
    command: >
      sh -c "./docs/scripts/generate_changelog.sh &&
             (cd docs; mkdocs build --clean) &&
             python manage.py collectstatic --noinput &&
             python manage.py wait_for_db &&
             python manage.py makemigrations core &&
             python manage.py migrate &&
             python manage.py initadmin &&
             python manage.py runserver 0.0.0.0:5000"
    environment:
      - POSTGRES_HOST=db
    env_file: .env
    depends_on:
      - db
  db:
    image: postgres:13.4-alpine
    hostname: db
    restart: unless-stopped
    env_file: .env
