version: "3"
volumes:
  pg_data:
  redis_data:
services:
  ui:
    build:
      context: ui
      args:
        GIT_VERSION: "${GIT_VERSION}"
        GIT_BRANCH: "${GIT_BRANCH}"
        GIT_LASTCOMMITDATE: "${GIT_LASTCOMMITDATE}"
    image: ui
    hostname: ui
    depends_on:
      - api
    restart: unless-stopped
    env_file: .env
  api:
    build:
      context: api
    hostname: api
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./api/app:/app
      - ./api/config:/config
      - ./api/plugins:/plugins
      - ./.git:/.git
      - ./data:/data:z
    environment:
      - POSTGRES_HOST=db
    env_file: .env
    depends_on:
      - db
    command: >
      sh -c "./docs/scripts/generate_changelog.sh &&
             (cd docs; mkdocs build --clean) &&
             python manage.py collectstatic --noinput &&
             python manage.py wait_for_db &&
             python manage.py makemigrations core &&
             python manage.py migrate &&
             python manage.py initadmin &&
             python manage.py runserver 0.0.0.0:5000"
  db:
    image: postgres:13.4-alpine
    hostname: db
    restart: unless-stopped
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  vep_rest:
    image: dameyerdave/vep-offline-rest
    volumes:
      - "${HOME}/vep_data:/opt/vep/.vep"
      - ./data/images:/opt/vep/src/ensembl-vep/images
    ports:
      - "5005:5005"
  redis:
    image: redis:7.0.0
    hostname: redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    # To start redis in persistent mode (every 60s a snapshot is stored)
    command: |
      sh -c 'redis-server --save 60 1 --loglevel warning'

  seqrepo:
    image: biocommons/seqrepo-rest-service
    hostname: seqrepo
    volumes:
      - "/usr/local/share/seqrepo:/usr/local/share/seqrepo"
    restart: unless-stopped

  disgenet:
    image: ethnexus/disgenet-ms
    ports:
      - "9077:9077"
    volumes:
      - ./data:/data:z
    secrets:
      - disgenet_creds
    env_file: .env
secrets:
  disgenet_creds:
    file: ./.disgenet_creds
