version: "3"

services:
  ui:
    build:
      context: ui
      args:
        GIT_VERSION: "${GIT_VERSION}"
        GIT_BRANCH: "${GIT_BRANCH}"
        GIT_LASTCOMMITDATE: "${GIT_LASTCOMMITDATE}"
    image: ui
    hostname: ui
    depends_on:
      - api
    restart: unless-stopped
    env_file: .env
  api:
    build:
      context: api
    hostname: api
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./api/app:/app
      - ./api/config:/config
      - ./api/plugins:/plugins
      - ./.git:/.git
      - ./data:/data
    environment:
      - POSTGRES_HOST=db
    env_file: .env
    depends_on:
      - db
    command: >
      sh -c "./docs/scripts/generate_changelog.sh &&
             (cd docs; mkdocs build --clean) &&
             python manage.py collectstatic --noinput &&
             python manage.py wait_for_db &&
             python manage.py makemigrations core &&
             python manage.py migrate &&
             python manage.py initadmin &&
             python manage.py runserver 0.0.0.0:5000"
  db:
    image: postgres:13.4-alpine
    hostname: db
    restart: unless-stopped
    env_file: .env
  vep_rest:
    image: dameyerdave/vep-offline-rest
    volumes:
      - "${HOME}/vep_data:/opt/vep/.vep"
    ports:
      - "5005:5005"
  redis:
    image: redis:7.0.0
    hostname: redis
    restart: unless-stopped

  seqrepo:
    image: biocommons/seqrepo-rest-service
    hostname: seqrepo
    volumes:
      - "/usr/local/share/seqrepo:/usr/local/share/seqrepo"
    restart: unless-stopped
