---
options:
  na_string: "."
sample:
  fields:
    - id
    - patient
    - tissue
variant:
  fields:
    - vrs_id
    - assembly
    - chromosome
    - start
    - end
    - allele_string:
        format: vep_allele_string
    - strand:
        format: vep_strand
    - variant_class:
        label: variant_class
    - extra__most_severe_consequence:
        label: Consequence
    - gene_names:
        label: Genes
    - annotations__clin_sig:
        label: clinical_significances
        highlight:
          benign: bg-green-5
          pathogenic: bg-red-5
    # - transcript_names:
    #     label: Transcripts
  search_fields:
    - start
    - transcripts__name
    - transcripts__gene__symbol
    - most_severe_consequence__term
  ordering:
    - chromosome
    - start
  filters:
    default:
      and:
        # only show variants that have transcripts associated
        - transcripts__isnull: false
        - or:
            - most_severe_consequence__term__in:
                - missense_variant
                - frameshift_variant
                - stop_gained
                - start_lost
            - most_severe_consequence__term__startswith: splice
            - most_severe_consequence__term__startswith: inframe
transcript:
  fields:
    - name
    - extra__gene:
        label: gene
    - hgvsg
    - hgvsc
    - hgvsp
    - ensembl_id
    - annotations__refseq_transcript_ids:
        label: refseq_id
    - annotations__consequence_terms:
        label: consequence
        format: beautify_list
    - annotations__impact:
    - annotations__biotype:
        format: beautify_string
  flags:
    # Defining flags needs a restart of the application
    canonical:
      rule:
        and:
          # If the transcript is canonical the canonical flag is attached
          - annotations__canonical: 1
      icon: favorite
    pick:
      rule:
        and:
          - annotations__pick: 1
      icon: task_alt
    mane:
      rule:
        and:
          - annotations__mane_select__isnull: false
      icon: star_rate
  search_fields:
    - gene__symbol
    - name
    - ensembl_id
    - hgvsc
    - hgvsp
  ordering:
    - name
  filters:
    default:
      and:
        # we show only protein_coding transcripts
        - annotations__biotype: protein_coding
  strategies:
    ranking: VepRanking
  custom_annotations:
    - id: analyze
      label: label.analyze
      type: Boolean
    - id: comment
      label: label.comment
      type: String
    - id: priority
      type: Select
      options:
        - { value: high, label: High }
        - { value: medium, label: Medium }
        - { value: low, label: Low }
gene:
  fields:
    - symbol
    - annotations__alias_symbol:
        label: aliases
    - annotations__prev_symbol:
        label: prevs
    - annotations__mane_select:
        label: mane
  search_fields:
    - symbol
    - ensembl_id
    - annotations__alias_symbol
    - annotations__prev_symbol
  ordering:
    - symbol
samplevariant:
  fields:
    - sample
    - variant
    - zygosity
  ordering:
    - sample__id
  # filters:
  #   default:
  #     and:
  #       # we show only protein_coding transcripts
  #       - variant__transcripts__annotations__biotype: protein_coding
import:
  tupro:
    strategy: vep
    format: tsv
    chromosome:
      field: SV-GENOME-POSITION
      regex: "chr([^:]+):[0-9]+"
    start:
      field: SV-GENOME-POSITION
      regex: "chr[^:]+:([0-9]+)"
    ref:
      field: SV-CDS-CHANGE
      regex: "[0-9-]+([ACGT])>[ACGT]"
    alt:
      field: SV-CDS-CHANGE
      regex: "[0-9-]+[ACGT]>([ACGT])"
    strand:
      field: STRAND
    transcript_id:
      field: TRANSCRIPT
  icarus:
    strategy: icarus
    format: tsv
    # this takes the importer module from modules/importer
    chromosome:
      field: Chromosome
      regex: "chr([^:]+)"
    start:
      field: Position
    ref:
      field: Ref
    alt:
      field: Alt
    # specific parameters for this strategy
    gene_info: '(?P<gene>[^\|]+)\|(?P<ensembl_ids>[^\|]+)\|(?P<strand>[^\|]+)\|(?P<pathways>[^\|]+)\|(?P<hsir>[^\|]+)\|(?P<tier>[^\|]+)\|(?P<custom_phenotypes>[^\|]+)\|(?P<mitochondrial>[^\|]+)\|(?P<gene_type>[^\|]+)\|(?P<omim_phenotypes>[^\|]+)\|(?P<orpha_phenotypes>[^\|]+)\|(?P<missense_info>[^\;]+)(?:;|$)'
    snv_info: '(?P<gene>[^\|]+)\|(?P<ensembl_id>[^\&]+)\&(?P<ref_seq_id>[^\&]+)\&(?P<rank>[^\|]+)\|(?P<dna_change>[^\|]+)\|(?P<protein_change>[^\|]+)\|(?P<variant_impact>[^\|]+)\|(?P<affected_exon>[^\|]+)\|(?P<max_ent_scan_ref>[^\|]+)\|(?P<max_ent_scan_alt>[^\|]+)\|(?P<max_ent_scan_diff>[^\|]+)\|(?P<revel_score>[^\|]+)\|(?P<ada_score>[^\|]+)\|(?P<rf_score>[^\|]+)\|(?P<protein_domains>[^\|]+)\|(?P<protein_domain_predictions>[^\|]+)\|(?P<clinical_significances>[^\|]+)\|(?P<clinvar_conflicts>[^\|]+)\|(?P<variant_ids>[^\|]+)\|(?P<gnom_ad3_infos>[^\|]+)\|(?P<gnom_ad2g_infos>[^\|]+)\|(?P<gnom_ad2e_infos>[^\|]+)\|(?P<ex_ac_infos>[^\|]+)\|(?P<variant_sub_type>[^\|]+)\|(?P<splicing_type>[^\|]+)\|(?P<repetitive_region_info>[^\|]+)\|(?P<hotspot_region_info>[^\|]+)\|(?P<autopvs1>[^;]+)(?:;|$)'
    cnv_info: '(?P<affected_genes>[^\|]+)\|(?P<variant_impact>[^\|]+)\|(?P<copy_number>[^\|]+)\|(?P<cnv_length>[^\|]+)\|(?P<cnv_start>[^\|]+)\|(?P<cnv_end>[^\|]+)\|(?P<dgv_info>[^\|]+)\|(?P<autopvs1>[^\|]+)$'
    # transcript:
    #   field: SNV-info
    #   multi_value_regex:
    #   ensemble_id:
    #     field: ensembl_id
    #   name:
    #     field:
    # sample_variant:
    #   zygosity:
    #     field: Zygosity
    #   coverage:
    #     field: ReadDepth
    #   percent_reads:
    #     field: Frequency
    #   annotations:
    #     fields:
    #       - AllelicDepthRef
    #       - AllelicDepthAlt
    #       - Mapping_quality
    #       - Probe_distance
    #       - Base_quality
    # strand:
    #   field: STRAND
    # transcripts:
    #   field:
