---
options:
  na_string: "."
variant:
  fields:
    - assembly
    - chromosome
    - start
    - end
    - allele_string:
        format: vep_allele_string
    - strand:
        format: vep_strand
    - extra__most_severe_consequence:
        label: Consequence
    - variant_type
    - extra__gene_names:
        label: Genes
    - extra__transcript_names:
        label: Transcripts
  search_fields:
    - transcripts__name
    - transcripts__gene__symbol
    - most_severe_consequence__term
transcript:
  fields:
    - name
    - gene
    - hgvsg
    - hgvsc
    - hgvsp
    - ensembl_id
    - annotations__refseq_transcript_ids:
        label: refseq_id
    - annotations__consequence_terms:
        label: consequence
    - annotations__impact:
    - annotations__biotype:
  search_fields:
    - gene__symbol
    - name
    - ensembl_id
    - hgvsc
    - hgvsp
gene:
  fields:
    - symbol
    - annotations__alias_symbol:
        label: aliases
    - annotations__prev_symbol:
        label: prevs
    - annotations__mane_select:
        label: mane
  search_fields:
    - symbol
    - ensembl_id
    - annotations__alias_symbol
    - annotations__prev_symbol
