# Generated by Django 4.0.3 on 2022-04-06 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gene',
            options={'ordering': ['symbol']},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['surename']},
        ),
        migrations.AlterModelOptions(
            name='sample',
            options={'ordering': ['sample_id']},
        ),
        migrations.AlterModelOptions(
            name='transcript',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='variant',
            options={'ordering': ['chromosome', 'start']},
        ),
        migrations.AlterModelOptions(
            name='variantconsequence',
            options={'ordering': ['term']},
        ),
    ]
