# Generated by Django 4.0.3 on 2022-05-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltranscript',
            name='refseq_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='transcript',
            name='refseq_id',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='historicaltranscript',
            name='ensembl_id',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='ensembl_id',
            field=models.TextField(null=True),
        ),
    ]
