# Generated by Django 4.0.3 on 2022-03-09 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantConsequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.TextField()),
                ('hr_term', models.TextField()),
                ('impact', models.CharField(choices=[('HIGH', 'HIGH'), ('MODERATE', 'MODERATE'), (
                    'MODIFIER', 'MODIFIER'), ('LOW', 'LOW')], max_length=8)),
                ('description', models.TextField()),
                ('accession', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='variant',
            name='most_severe_consequence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='variants', to='core.variantconsequence'),
        )
    ]
