# Generated by Django 4.0.3 on 2022-07-18 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvariantevidence',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalvariantevidence',
            name='variant',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.variant'),
        ),
        migrations.AddField(
            model_name='historicalvariant',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalvariant',
            name='most_severe_consequence',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.variantconsequence'),
        ),
        migrations.AddField(
            model_name='historicaltranscriptevidence',
            name='evidence',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.evidence'),
        ),
        migrations.AddField(
            model_name='historicaltranscriptevidence',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltranscriptevidence',
            name='transcript',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.transcript'),
        ),
        migrations.AddField(
            model_name='historicaltranscript',
            name='gene',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.gene'),
        ),
        migrations.AddField(
            model_name='historicaltranscript',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltranscript',
            name='variant',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.variant'),
        ),
        migrations.AddField(
            model_name='historicalsamplevariant',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalsamplevariant',
            name='sample',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.sample'),
        ),
        migrations.AddField(
            model_name='historicalsamplevariant',
            name='variant',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.variant'),
        ),
        migrations.AddField(
            model_name='historicalsample',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalsample',
            name='patient',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.patient'),
        ),
        migrations.AddField(
            model_name='historicalphenotype',
            name='gene',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.gene'),
        ),
        migrations.AddField(
            model_name='historicalphenotype',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalgene',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalevidence',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldiseaseevidence',
            name='disease',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.disease'),
        ),
        migrations.AddField(
            model_name='historicaldiseaseevidence',
            name='evidence',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.evidence'),
        ),
        migrations.AddField(
            model_name='historicaldiseaseevidence',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldisease',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='evidence',
            unique_together={('reference', 'source')},
        ),
        migrations.AddField(
            model_name='diseaseevidence',
            name='disease',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disease_evidences', to='core.disease'),
        ),
        migrations.AddField(
            model_name='diseaseevidence',
            name='evidence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disease_evidences', to='core.evidence'),
        ),
        migrations.AddField(
            model_name='diseasediseaseclass',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_disease_classes', to='core.disease'),
        ),
        migrations.AddField(
            model_name='diseasediseaseclass',
            name='disease_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_disease_classes', to='core.diseaseclass'),
        ),
        migrations.AlterUniqueTogether(
            name='variantevidence',
            unique_together={('variant', 'evidence')},
        ),
        migrations.AlterUniqueTogether(
            name='variantdisease',
            unique_together={('disease', 'variant')},
        ),
        migrations.AlterUniqueTogether(
            name='variantannotation',
            unique_together={('scope', 'property')},
        ),
        migrations.AlterUniqueTogether(
            name='variant',
            unique_together={('assembly', 'chromosome', 'start', 'end', 'allele_string')},
        ),
        migrations.AlterUniqueTogether(
            name='transcriptevidence',
            unique_together={('transcript', 'evidence')},
        ),
        migrations.AlterUniqueTogether(
            name='transcript',
            unique_together={('variant', 'ensembl_id')},
        ),
        migrations.AlterUniqueTogether(
            name='samplevariantannotation',
            unique_together={('scope', 'property')},
        ),
        migrations.AlterUniqueTogether(
            name='samplevariant',
            unique_together={('sample', 'variant')},
        ),
        migrations.AlterUniqueTogether(
            name='phenotype',
            unique_together={('gene', 'phenotype')},
        ),
        migrations.AlterUniqueTogether(
            name='diseaseevidence',
            unique_together={('disease', 'evidence')},
        ),
    ]
