# Generated by Django 4.0.3 on 2022-03-09 14:26

from django.db import migrations
from django.core.management import call_command


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_variantconsequence_and_more'),
    ]

    def load_variant_consequences(apps, schema_editor):
        call_command("loaddata", "variant_consequences.yaml")

    operations = [
        migrations.RunPython(load_variant_consequences)
    ]
