# Generated by Django 4.0.3 on 2022-04-08 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_phenotype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phenotype',
            options={'ordering': ['phenotype']},
        ),
        migrations.AlterModelOptions(
            name='samplevariant',
            options={'ordering': ['sample__sample_id']},
        ),
    ]
