# Generated by Django 4.0.3 on 2022-03-09 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_load_variant_consequences'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variant',
            old_name='alt',
            new_name='allele_string',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='annotations',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='gene',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='position',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='ref',
        ),
        migrations.AddField(
            model_name='gene',
            name='ensembl_id',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='end',
            field=models.IntegerField(
                default=0, help_text='The end of the variant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variant',
            name='start',
            field=models.IntegerField(
                default=0, help_text='The start of the variant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variant',
            name='variant_type',
            field=models.CharField(choices=[(
                'SNV', 'SNV'), ('CNV', 'CNV'), ('DEL', 'DEL')], default='SNV', max_length=3),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BaseTranscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('ensembl_id', models.TextField(null=True)),
                ('hgvsg', models.TextField()),
                ('hgvsc', models.TextField()),
                ('hgvsp', models.TextField()),
                ('annotations', models.JSONField()),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='transcripts', to='core.gene')),
                ('variant', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='core.variant')),
            ],
        ),
    ]
