# Generated by Django 4.0.3 on 2022-05-20 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_historicalvariantevidence_variantevidence'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='evidence',
            unique_together={('reference', 'source')},
        ),
    ]
