# Generated by Django 4.0.3 on 2022-05-20 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_alter_evidence_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalEvidence',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('annotations', models.JSONField(null=True)),
                ('custom_annotations', models.JSONField(null=True)),
                ('reference', models.TextField()),
                ('source', models.CharField(choices=[('Unknown', 'Unknown'), ('Pubmed', 'Pubmed'), ('GoogleScholar', 'GoogleScholar'), ('Internet', 'Internet'), ('Internal', 'Internal')], default='Unknown', max_length=13)),
                ('title', models.TextField()),
                ('summary', models.TextField()),
                ('evidence_date', models.DateTimeField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical evidence',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
