# Generated by Django 4.0.3 on 2022-03-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_basetranscript_transcript'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='name',
            field=models.TextField(default='N/A'),
            preserve_default=False,
        ),
    ]
