# Generated by Django 4.0.3 on 2022-03-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_transcript_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcript',
            name='hgvsc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='hgvsg',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='hgvsp',
            field=models.TextField(null=True),
        ),
    ]
