# Generated by Django 4.0.3 on 2022-04-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_created_on_historicaltranscriptevidence_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={},
        ),
        migrations.AlterModelOptions(
            name='phenotype',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sample',
            options={},
        ),
        migrations.AlterModelOptions(
            name='samplevariant',
            options={},
        ),
        migrations.AlterModelOptions(
            name='transcript',
            options={},
        ),
        migrations.AlterModelOptions(
            name='variant',
            options={},
        ),
        migrations.AddField(
            model_name='historicalsamplevariant',
            name='coverage',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='historicalsamplevariant',
            name='percent_reads',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='historicaltranscript',
            name='strand',
            field=models.CharField(choices=[('+', '+'), ('-', '-')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='samplevariant',
            name='coverage',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='samplevariant',
            name='percent_reads',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='transcript',
            name='strand',
            field=models.CharField(choices=[('+', '+'), ('-', '-')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='historicalvariant',
            name='strand',
            field=models.CharField(choices=[('+', '+'), ('-', '-')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='strand',
            field=models.CharField(choices=[('+', '+'), ('-', '-')], max_length=1, null=True),
        ),
    ]
