# Generated by Django 4.0.3 on 2022-05-24 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_historicalvariant_ensembl_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalvariant',
            name='ensembl_id',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='ensembl_id',
        ),
    ]
