# Generated by Django 4.0.3 on 2022-03-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_transcript_hgvsc_alter_transcript_hgvsg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gene',
            name='annotations',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='annotations',
            field=models.JSONField(null=True),
        ),
    ]
