# Generated by Django 4.0.3 on 2022-03-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_gene_annotations_alter_transcript_annotations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gene',
            name='symbol',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
