# Generated by Django 4.0.3 on 2022-05-24 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_historicalvariant_variant_class_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalvariant',
            name='variant_type',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='variant_type',
        ),
    ]
