# Generated by Django 4.0.3 on 2022-04-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_historicaltranscript_strand_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gene',
            options={},
        ),
        migrations.AlterModelOptions(
            name='variantconsequence',
            options={},
        ),
        migrations.AddField(
            model_name='gene',
            name='entrez_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='historicalgene',
            name='entrez_id',
            field=models.IntegerField(null=True),
        ),
    ]
