# Generated by Django 4.0.3 on 2022-05-24 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_historicalvariant_variant_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltranscript',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='transcript',
            name='rank',
        ),
    ]
