# Generated by Django 4.0.3 on 2022-05-03 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_gene_options_alter_variantconsequence_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsamplevariant',
            name='annotations',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='historicalsamplevariant',
            name='custom_annotations',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='samplevariant',
            name='annotations',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='samplevariant',
            name='custom_annotations',
            field=models.JSONField(null=True),
        ),
    ]
