# Generated by Django 4.0.3 on 2022-03-11 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_gene_symbol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcript',
            name='hgvsg',
        ),
    ]
