# Generated by Django 4.0.3 on 2022-05-24 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_historicaltranscript_rank_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transcript',
            unique_together={('variant', 'ensembl_id')},
        ),
    ]
