# Generated by Django 4.0.3 on 2022-05-03 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_historicalsamplevariant_annotations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsamplevariant',
            name='coverage',
        ),
        migrations.RemoveField(
            model_name='historicalsamplevariant',
            name='percent_reads',
        ),
        migrations.RemoveField(
            model_name='historicalsamplevariant',
            name='zygosity',
        ),
        migrations.RemoveField(
            model_name='samplevariant',
            name='coverage',
        ),
        migrations.RemoveField(
            model_name='samplevariant',
            name='percent_reads',
        ),
        migrations.RemoveField(
            model_name='samplevariant',
            name='zygosity',
        ),
    ]
