# Generated by Django 4.0.3 on 2022-03-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_patient_sample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcript',
            name='ensembl_id',
            field=models.TextField(null=True, unique=True),
        ),
    ]
