# Generated by Django 4.0.3 on 2022-06-03 15:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_transcript_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalphenotype',
            name='inheritance_mode',
        ),
        migrations.AddField(
            model_name='historicalphenotype',
            name='inheritance_modes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), null=True, size=None),
        ),
        migrations.AddField(
            model_name='phenotype',
            name='inheritance_modes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), null=True, size=None),
        ),
        migrations.AlterUniqueTogether(
            name='phenotype',
            unique_together={('gene', 'phenotype')},
        ),
        migrations.RemoveField(
            model_name='phenotype',
            name='inheritance_mode',
        ),
    ]
