# Generated by Django 4.0.3 on 2022-05-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_historicalsamplevariant_coverage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsamplevariant',
            name='zygosity',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('Homozygous', 'Homozygous'), ('Heterozygous', 'Heterozygous'), ('Hemizygous', 'Hemizygous'), ('Homoplasmic', 'Homoplasmic'), ('Heteroplasmic', 'Heteroplasmic')], default='Unknown', max_length=13),
        ),
        migrations.AddField(
            model_name='samplevariant',
            name='zygosity',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('Homozygous', 'Homozygous'), ('Heterozygous', 'Heterozygous'), ('Hemizygous', 'Hemizygous'), ('Homoplasmic', 'Homoplasmic'), ('Heteroplasmic', 'Heteroplasmic')], default='Unknown', max_length=13),
        ),
    ]
