# Generated by Django 4.0.3 on 2022-03-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_transcript_ensembl_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gene',
            name='symbol',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
