# Generated by Django 4.0.3 on 2022-05-04 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_historicalsamplevariant_zygosity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsamplevariant',
            name='zygosity',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('Homozygous', 'Homozygous'), ('Heterozygous', 'Heterozygous'), ('Hemizygous', 'Hemizygous'), ('Homoplasmic', 'Homoplasmic'), ('Heteroplasmic', 'Heteroplasmic'), ('Zero_coverage_region', 'Zero_coverage_region')], default='Unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='samplevariant',
            name='zygosity',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('Homozygous', 'Homozygous'), ('Heterozygous', 'Heterozygous'), ('Hemizygous', 'Hemizygous'), ('Homoplasmic', 'Homoplasmic'), ('Heteroplasmic', 'Heteroplasmic'), ('Zero_coverage_region', 'Zero_coverage_region')], default='Unknown', max_length=20),
        ),
    ]
