# Generated by Django 4.0.3 on 2022-05-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_historicalsamplevariant_zygosity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltranscript',
            name='variant',
        ),
        migrations.RemoveField(
            model_name='transcript',
            name='variant',
        ),
        migrations.AddField(
            model_name='transcript',
            name='variant',
            field=models.ManyToManyField(related_name='transcripts', to='core.variant'),
        ),
    ]
