# Generated by Django 4.0.3 on 2022-03-31 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_gene_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcript',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcripts', to='core.variant'),
        ),
    ]
