# Generated by Django 4.0.3 on 2022-06-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_historicalsamplevariant_zygosity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsamplevariant',
            name='zygosity',
            field=models.CharField(choices=[('Homozygous', 'Homozygous'), ('Heterozygous', 'Heterozygous'), ('Hemizygous', 'Hemizygous'), ('Homoplasmic', 'Homoplasmic'), ('Heteroplasmic', 'Heteroplasmic'), ('Zero_coverage_region', 'Zero_coverage_region')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='samplevariant',
            name='zygosity',
            field=models.CharField(choices=[('Homozygous', 'Homozygous'), ('Heterozygous', 'Heterozygous'), ('Hemizygous', 'Hemizygous'), ('Homoplasmic', 'Homoplasmic'), ('Heteroplasmic', 'Heteroplasmic'), ('Zero_coverage_region', 'Zero_coverage_region')], default=None, max_length=20, null=True),
        ),
    ]
