# Generated by Django 4.0.3 on 2022-05-05 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_historicaltranscript_rank_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcript',
            name='variant',
        ),
    ]
