# Generated by Django 4.0.3 on 2022-06-08 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_disease_historicalvariant_dbsnp_id_variant_dbsnp_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='class_name',
            field=models.TextField(default='xx'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaldisease',
            name='class_name',
            field=models.TextField(default='xx'),
            preserve_default=False,
        ),
    ]
