# Generated by Django 4.0.3 on 2022-06-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_disease_class_name_historicaldisease_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantconsequence',
            name='consequence_ranking',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
