# Generated by Django 4.0.3 on 2022-06-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_historicalsamplevariant_causative_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsamplevariant',
            name='causative',
            field=models.BooleanField(default=False, help_text='If true This is a causative variant in this sample'),
        ),
        migrations.AlterField(
            model_name='samplevariant',
            name='causative',
            field=models.BooleanField(default=False, help_text='If true This is a causative variant in this sample'),
        ),
    ]
