# Generated by Django 4.0.3 on 2022-06-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_historicalsamplevariant_causative_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='_class',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='disease',
            name='class_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='historicaldisease',
            name='_class',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldisease',
            name='class_name',
            field=models.TextField(null=True),
        ),
    ]
