# Generated by Django 4.0.3 on 2022-06-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_disease__class_alter_disease_class_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='semantic_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldisease',
            name='semantic_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
