# Generated by Django 4.0.3 on 2022-06-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_disease_semantic_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='year_final',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='disease',
            name='year_initial',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='historicaldisease',
            name='year_final',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='historicaldisease',
            name='year_initial',
            field=models.IntegerField(null=True),
        ),
    ]
