# Generated by Django 4.0.3 on 2022-06-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_disease_year_final_alter_disease_year_initial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='ei',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='historicaldisease',
            name='ei',
            field=models.FloatField(null=True),
        ),
    ]
