# Generated by Django 4.0.3 on 2022-06-30 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_disease_ei_alter_historicaldisease_ei'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=20, unique=True)),
                ('name', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='disease',
            name='_class',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='ei',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='score',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='source',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='year_final',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='year_initial',
        ),
        migrations.RemoveField(
            model_name='historicaldisease',
            name='_class',
        ),
        migrations.RemoveField(
            model_name='historicaldisease',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='historicaldisease',
            name='ei',
        ),
        migrations.RemoveField(
            model_name='historicaldisease',
            name='score',
        ),
        migrations.RemoveField(
            model_name='historicaldisease',
            name='source',
        ),
        migrations.RemoveField(
            model_name='historicaldisease',
            name='year_final',
        ),
        migrations.RemoveField(
            model_name='historicaldisease',
            name='year_initial',
        ),
        migrations.CreateModel(
            name='DiseaseDiseaseClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_disease_classes', to='core.disease')),
                ('disease_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_disease_classes', to='core.diseaseclass')),
            ],
        ),
    ]
