# Generated by Django 4.0.3 on 2022-07-01 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_diseaseclass_remove_disease__class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='semantic_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldisease',
            name='semantic_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
