# Generated by Django 4.0.3 on 2022-07-06 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_disease_semantic_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=50)),
                ('property', models.CharField(max_length=50)),
                ('value', models.JSONField(null=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_annotations', to='core.variant')),
            ],
            options={
                'unique_together': {('scope', 'property')},
            },
        ),
        migrations.CreateModel(
            name='SampleVariantAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=50)),
                ('property', models.CharField(max_length=50)),
                ('value', models.JSONField(null=True)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_variant_annotations', to='core.sample')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_variant_annotations', to='core.variant')),
            ],
            options={
                'unique_together': {('scope', 'property')},
            },
        ),
    ]
