# Generated by Django 4.0.3 on 2022-07-06 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_historicaldiseaseevidence_diseaseevidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseaseevidence',
            name='disease',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disease_evidences', to='core.disease'),
        ),
        migrations.AlterField(
            model_name='historicaldiseaseevidence',
            name='disease',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.disease'),
        ),
    ]
