FROM node:17-alpine

ARG GIT_VERSION
ARG GIT_BRANCH
ARG GIT_LASTCOMMITDATE
ENV VITE_APP_VERSION=${GIT_VERSION}
ENV VITE_APP_BRANCH=${GIT_BRANCH}
ENV VITE_APP_LASTCOMMITDATE=${GIT_LASTCOMMITDATE}

ENV PATH="$PATH:/app/node_modules/.bin"

COPY ./app /app
WORKDIR /app
RUN npm install -g npm@latest
RUN yarn global add vite

RUN yarn install
RUN npx browserslist@latest --update-db